# Generated by Django 5.2.17 on 2026-09-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='is_public_to_recruiters',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='show_contact_info',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='show_education',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='show_experience',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='show_links',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='show_location',
        ),
    ]
